
job('Inventory-Via-DSL') {
    description("Inventory project job generated by the DSL on ${new Date()}, The project hosted on github")
    scm {
        git("https://github.com/aidenkimgj/Inventory.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.war'
    }
}
